
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author GGS
 */
public class Promo2017 extends javax.swing.JFrame {

    
     
     public DefaultTableModel dt;
    private String id;
    private String nom,prenom,sexe;
    private String date,lieu,nationalite;
    private String faculte,departement,filiere,niveau;
    private int i;
    Connection con=null;
    Statement st=null;
    ResultSet rs=null;
    public Promo2017() {
        initComponents();
        this.setSize(new Dimension (950,670));
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txti = new javax.swing.JTextField();
        txtn = new javax.swing.JTextField();
        txtp = new javax.swing.JTextField();
        cmbs = new javax.swing.JComboBox();
        txtd = new javax.swing.JTextField();
        txtl = new javax.swing.JTextField();
        txtna = new javax.swing.JTextField();
        cmbf = new javax.swing.JComboBox();
        cmbd = new javax.swing.JComboBox();
        cmbfi = new javax.swing.JComboBox();
        cmbni = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btne = new javax.swing.JButton();
        btnm = new javax.swing.JButton();
        btns = new javax.swing.JButton();
        btna = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        comborech = new javax.swing.JComboBox();
        txtrech = new javax.swing.JTextField();
        btnrech = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 40, 11, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Nom");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 80, 28, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Prenom");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 130, 48, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Sexe");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 180, 29, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Date_de_naissance");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 210, 116, 17);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Lieu_de_naissance");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 250, 129, 17);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Nationalité");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 300, 67, 17);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Faculté");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 360, 45, 17);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Departement");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 390, 81, 17);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setText("Filiere");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 420, 40, 17);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel11.setText("Niveau");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 460, 42, 17);

        txti.setBackground(new java.awt.Color(255, 255, 0));
        txti.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txti);
        txti.setBounds(90, 40, 130, 23);

        txtn.setBackground(new java.awt.Color(255, 255, 0));
        txtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtn);
        txtn.setBounds(90, 80, 130, 23);

        txtp.setBackground(new java.awt.Color(255, 255, 0));
        txtp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtp);
        txtp.setBounds(90, 120, 130, 30);

        cmbs.setBackground(new java.awt.Color(51, 255, 102));
        cmbs.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbs.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin", "Feminin", "Autres" }));
        getContentPane().add(cmbs);
        cmbs.setBounds(90, 170, 130, 23);

        txtd.setBackground(new java.awt.Color(255, 255, 0));
        txtd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtd);
        txtd.setBounds(130, 200, 90, 23);

        txtl.setBackground(new java.awt.Color(255, 255, 0));
        txtl.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtl);
        txtl.setBounds(140, 250, 80, 23);

        txtna.setBackground(new java.awt.Color(255, 255, 0));
        txtna.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtna);
        txtna.setBounds(110, 300, 120, 23);

        cmbf.setBackground(new java.awt.Color(51, 255, 102));
        cmbf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "FS", "FSEG", "FALSH", "ENSAI", "IUT" }));
        getContentPane().add(cmbf);
        cmbf.setBounds(100, 350, 120, 23);

        cmbd.setBackground(new java.awt.Color(51, 255, 102));
        cmbd.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbd.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MATHEMATIQUE ET INFORMATIQUE" }));
        getContentPane().add(cmbd);
        cmbd.setBounds(90, 390, 140, 23);

        cmbfi.setBackground(new java.awt.Color(51, 255, 102));
        cmbfi.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbfi.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AR", "MA" }));
        getContentPane().add(cmbfi);
        cmbfi.setBounds(80, 420, 140, 23);

        cmbni.setBackground(new java.awt.Color(51, 255, 102));
        cmbni.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cmbni.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "I", "II", "III", "MI", "MII", "DOCTORAT" }));
        getContentPane().add(cmbni);
        cmbni.setBounds(80, 450, 140, 23);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8", "Title 9", "Title 10", "Title 11"
            }
        ));
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(250, 40, 620, 430);

        btne.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btne.setText("Enregistrer");
        btne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneActionPerformed(evt);
            }
        });
        getContentPane().add(btne);
        btne.setBounds(30, 490, 130, 50);

        btnm.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnm.setText("Modifier");
        btnm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmActionPerformed(evt);
            }
        });
        getContentPane().add(btnm);
        btnm.setBounds(20, 570, 150, 50);

        btns.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btns.setText("Supprimer");
        btns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsActionPerformed(evt);
            }
        });
        getContentPane().add(btns);
        btns.setBounds(200, 500, 130, 50);

        btna.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btna.setText("Actualiser");
        btna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaActionPerformed(evt);
            }
        });
        getContentPane().add(btna);
        btna.setBounds(200, 570, 130, 50);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Promotion2017_Des_Etudiants_De_L'Université_De_Ngaoundere");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 0, 550, 30);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Lister");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 540, 110, 40);

        comborech.setEditable(true);
        comborech.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        comborech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "id", "Nom", "Prenom", "Sexe", "Date_de_naissance", "Lieu_de_naissance", "Nationalité", "Faculte", "Departement", "Filiere", "Niveau" }));
        getContentPane().add(comborech);
        comborech.setBounds(480, 520, 160, 23);

        txtrech.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(txtrech);
        txtrech.setBounds(490, 580, 140, 23);

        btnrech.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        btnrech.setText("Rechercher");
        btnrech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrechActionPerformed(evt);
            }
        });
        getContentPane().add(btnrech);
        btnrech.setBounds(690, 540, 103, 25);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/windows_8_simple_background-wallpaper-1366x768(1).jpg"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, 0, 910, 640);

        jLabel14.setText("jLabel14");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(0, 0, 1020, 730);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
    Class.forName("com.mysql.jdbc.Driver");
    con=DriverManager.getConnection("jdbc:mysql://localhost:3306/promotion","root","");
    st=con.createStatement();
   
    dt=new DefaultTableModel();
    dt.addColumn("id");
    dt.addColumn("Nom");
    dt.addColumn("Prenom");
    dt.addColumn("Sexe");
    dt.addColumn("Date_De_naissance");
    dt.addColumn("Lieu_De_naissance");
    dt.addColumn("Nationalite");
    dt.addColumn("Faculte");
    dt.addColumn("Departement");
    dt.addColumn("Filiere");
    dt.addColumn("Niveau");
    table.setModel(dt);
    Affiche();
   // i=0;
    Deplacer(i);
    
    
        }catch (Exception e){
          System.err.println("erreur"+e.getMessage());
          JOptionPane.showMessageDialog(null,"ereur connexion/n"+e.getMessage());
          
          
        }
                                    

    }//GEN-LAST:event_formWindowOpened

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        try{
        i=table.getSelectedRow();
        Deplacer(i);
    }catch(Exception e){
        JOptionPane.showMessageDialog(null,"ereur selectionne etudiant/n"+e.getMessage());
    }
    }//GEN-LAST:event_tableMouseClicked

    private void btneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneActionPerformed
       try{
        String sql="INSERT INTO etudiant (id,Nom,Prenom,Sexe,Datenaissance,Lieunaissance,Nationalite,Faculte,Departement,Filiere,Niveau)VALUES(?,?,?,?,?,?,?,?,?,?,?)";
      PreparedStatement ps=con.prepareStatement(sql);
      ps.setString(1,txti.getText());
      ps.setString(2,txtn.getText());
       ps.setString(3,txtp.getText());
      ps.setString(4,cmbs.getSelectedItem().toString());
      ps.setString(5,txtd.getText());
       ps.setString(6,txtl.getText());
       ps.setString(7,txtn.getText());
       ps.setString(8,cmbf.getSelectedItem().toString());
      ps.setString(9,cmbd.getSelectedItem().toString());
      ps.setString(10,cmbfi.getSelectedItem().toString());
      ps.setString(11,cmbni.getSelectedItem().toString());
        ps.executeUpdate();
        Affiche();
      JOptionPane.showMessageDialog(null,"etudiant ajoute");
    }                                          
catch(Exception e){
       JOptionPane.showMessageDialog(null,"ereur ajouter etudiant/n"+e.getMessage());
         System.err.println(""+e.getMessage());
     }   
    }//GEN-LAST:event_btneActionPerformed

    private void btnmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmActionPerformed
         try{
        if( JOptionPane.showConfirmDialog(null,"confirmer la modification","modificationsur un etudiant",
               JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
           st.executeUpdate("UPDATE etudiant SET Nom='"+txtn.getText()+"',Prenom='"+txtp.getText()+
           "',Sexe='"+cmbs.getSelectedItem().toString()+"' ,Datenaissance='"+txtd.getText()+"',Lieunaissance='"+txtl.getText()+"',Nationalite=' "+txtna.getText()+
            "',Faculte='"+cmbf.getSelectedItem().toString()+"',Departement='"+cmbd.getSelectedItem().toString()+"',Filiere='"+cmbfi.getSelectedItem().toString()+
                   "',Filiere='"+cmbni.getSelectedItem().toString()+"' where id= '"+txti.getText()+"' ");
           Affiche();
       }
   }catch (Exception e){
          System.err.println("erreur"+e.getMessage());
          JOptionPane.showMessageDialog(null,"ereur modifier/n"+e.getMessage());
    }    
    }//GEN-LAST:event_btnmActionPerformed

    private void btnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsActionPerformed
        try{
     if(JOptionPane.showConfirmDialog(null,"attention"+ " voulez vous supprimer cet etudiant?","Suprimer etuidant",
            JOptionPane.YES_NO_OPTION)==JOptionPane.OK_OPTION){
         
          st.executeUpdate("Delete from etudiant where id=' " +txti.getText()+"'");
          Affiche();
     }  
   }catch (Exception e){
         JOptionPane.showMessageDialog(null,"ereur supprimer etudiant/n"+e.getMessage());
    }                      
    }//GEN-LAST:event_btnsActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaActionPerformed
       Actualiser();
    }//GEN-LAST:event_btnaActionPerformed

    private void btnrechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrechActionPerformed
           //Code du bouton Rechercher
  try{
      dt.setRowCount(0);//pour vider le tableau
      Statement st = con.createStatement();
      ResultSet rs = st.executeQuery("SELECT * FROM etudiant0 WHERE "+combo()
              +" like '%"+txtrech.getText()+"%'");
      while(rs.next()){
          id=rs.getString("id");
          nom=rs.getString(2);
          prenom=rs.getString(3);
          sexe=rs.getString(4);
          date=rs.getString(5);
          lieu=rs.getString(6);
          nationalite=rs.getString(7);
          faculte=rs.getString(8);
          departement=rs.getString(9);
          filiere=rs.getString(10);
          niveau=rs.getString(11);
         
          Object [] t ={id,nom,prenom,date,lieu,nationalite,faculte,departement,filiere,niveau,sexe};
          dt.addRow(t);
          
      }
      if(dt.getRowCount()==0){
          JOptionPane.showMessageDialog(null, "Aucune etudiant0");
          Afficher();
          
      }else{
          i=0;
          Deplacer(i);      
      }
  }  catch(Exception m){JOptionPane.showInternalMessageDialog(null,""+m.getMessage() );
      
  }
    
    }//GEN-LAST:event_btnrechActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Promo2017.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Promo2017.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Promo2017.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Promo2017.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Promo2017().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btna;
    private javax.swing.JButton btne;
    private javax.swing.JButton btnm;
    private javax.swing.JButton btnrech;
    private javax.swing.JButton btns;
    private javax.swing.JComboBox cmbd;
    private javax.swing.JComboBox cmbf;
    private javax.swing.JComboBox cmbfi;
    private javax.swing.JComboBox cmbni;
    private javax.swing.JComboBox cmbs;
    private javax.swing.JComboBox comborech;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private javax.swing.JTextField txtd;
    private javax.swing.JTextField txti;
    private javax.swing.JTextField txtl;
    private javax.swing.JTextField txtn;
    private javax.swing.JTextField txtna;
    private javax.swing.JTextField txtp;
    private javax.swing.JTextField txtrech;
    // End of variables declaration//GEN-END:variables
String combo() {
    switch (comborech.getSelectedIndex()){
        case 0: return "id";
        case 1: return "Nom";
        case 2: return "Prenom";
        case 3: return "Sexe";
        case 4: return "Datenaissance";
        case 5: return "Lieunaissance";
        case 6: return "Nationalite";
        case 7: return "Faculte";
        case 8: return "Departement";
        case 9: return "Filiere";
        case 10: return "Niveau";
        
           
    }
    return "";
} 
    private void Affiche() {
        
        try{
            dt.setRowCount(0);
            rs=st.executeQuery("Select* From etudiant");
            
 while(rs.next()){
    id=rs.getString("id");
     nom=rs.getString("Nom");
     prenom=rs.getString("Prenom");
     sexe=rs.getString("Sexe");
     date=rs.getString("Datenaissance");
     lieu=rs.getString("Lieunaissance");
     nationalite=rs.getString("Nationalite");
     faculte=rs.getString("Faculte");
     departement=rs.getString("Departement");
     filiere=rs.getString("Filiere");
     niveau=rs.getString("Niveau");
     st=con.createStatement();
     Object[] t= {id,nom,prenom,sexe,date,lieu,nationalite,faculte,departement,filiere,niveau } ;  
     dt.addRow(t);
 }
     
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Erreur afficher la liste des etudiants\n" +e.getMessage());
        }
    }

    private void Deplacer(int i) {
       try{
      txti.setText(dt.getValueAt(i, 0).toString());
      txtn.setText(dt.getValueAt(i, 1).toString());
      txtp.setText(dt.getValueAt(i, 2).toString());
    cmbs.setSelectedItem(dt.getValueAt(i, 3).toString());
     txtd.setText(dt.getValueAt(i, 4).toString());
     txtl.setText(dt.getValueAt(i, 5).toString());
     txtna.setText(dt.getValueAt(i, 6).toString());
     cmbf.setSelectedItem(dt.getValueAt(i, 7).toString());
      cmbd.setSelectedItem(dt.getValueAt(i, 8).toString());
       cmbfi.setSelectedItem(dt.getValueAt(i, 9).toString());
       cmbni.setSelectedItem(dt.getValueAt(i, 10).toString());
 
   
}
  catch(Exception e){
      JOptionPane.showMessageDialog(null,"Erreur de deplacement etudiant"+e.getMessage());
  }
    }
    private void Actualiser(){
     txti.setText("");
    txtn.setText("");
    txtp.setText("");
    cmbs.setSelectedItem(1);
    txtl.setText("");
    txtd.setText("");
    txtna.setText("");
    cmbf.setSelectedItem(1);
    cmbd.setSelectedItem(1);
    cmbfi.setSelectedItem(1);
     cmbni.setSelectedItem(1);
   // txtde.setText("");
    //txtfi.setText("");
    //jrbm.isSelected();
   // jrbf.isSelected();
    
                                     

}

}
